// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRbxE6Jer4Ze1S1tmU8r2R5RcmKAHCbk',
    appId: '1:878573760241:web:a4b6cab65549d6b6720350',
    messagingSenderId: '878573760241',
    projectId: 'quicksummary-e85ef',
    authDomain: 'quicksummary-e85ef.firebaseapp.com',
    storageBucket: 'quicksummary-e85ef.appspot.com',
    measurementId: 'G-TW3E0VP1FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi00hpBNezPuBO38GKAENYiWLTrL5s_7g',
    appId: '1:878573760241:android:e37227e299b188cb720350',
    messagingSenderId: '878573760241',
    projectId: 'quicksummary-e85ef',
    storageBucket: 'quicksummary-e85ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD89EDYjE3ty32Xnri4nZX8Tq7opixRoAY',
    appId: '1:878573760241:ios:2b440b8f4577dbbc720350',
    messagingSenderId: '878573760241',
    projectId: 'quicksummary-e85ef',
    storageBucket: 'quicksummary-e85ef.appspot.com',
    iosClientId:
        '878573760241-65j1rifqkls0glqthmbamagqu36a9qao.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicksummary',
  );
}
